config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  resources :quotes do
    member do
      get "find_author"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company

  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  # The signed stream name is generated from the array returned by the lambda
  # that is the first argument of the `broadcasts_to` method. In general:
  # 1. Users who share broadcastings should have the lambda return an array with the same values.
  # 2. Users who shouldn't share broadcastings should have the lambda return an array with different values.
  broadcasts_to ->(quote) { [quote.company, "quotes"] }, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :validatable
  # For now, we will comment out the below Devise modules since we just need
  # users in our seeds and a way to login.
  # :recoverable, :rememberable, :registerable

  belongs_to :company

  def name
    email.split("@").first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Devise's `authenticate_user!` method will first check if the user
  # is authenticated (logged in). If not, it will redirect the user
  # to the sign-in page.
  before_action :authenticate_user!, unless: :devise_controller?

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in? # user_signed_in? is from devise
  end

  helper_method :current_company
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :find_author]

  def index
    @quotes = current_company.quotes.ordered
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    render partial: "form", locals: { quote: @quote }
  end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully updated." }
        format.turbo_stream
      end

    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream
    end
  end

  def find_author
    outcome = Quotes::FindAuthor.run(quote: @quote)

    if outcome.valid?
      @ai_response = outcome.result

      respond_to do |format|
        format.html do
          render "quotes/find_author", formats: [:turbo_stream]
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end

  def client
    OpenAI::Client.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar__brand">
      <%= current_company.name %>
    </div>
    <div class="navbar__name">
      <%= current_user.name %>
    </div>
    <%= button_to "Sign out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in",
                new_user_session_path,
                class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <!-- We don't care about flash messages for now -->
    <!--    <div id="flash" class="flash">-->
          <%#= render "layouts/flash" %>
    <!--    </div>-->

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<main class="container">
  <div class="home">
    <h1>Quote Finder</h1>

    <p>A blazing fast quote finder built with Hotwire</p>

    <% if user_signed_in? %>
      <%= link_to "View quotes", quotes_path, class: "btn btn--dark" %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark" %>
    <% end %>
  </div>
</main>

app/views/quotes/_api_response.html.erb
<%= @api_response %>

app/views/quotes/_form.html.erb
<%= turbo_frame_tag(quote) do %>
  <%= simple_form_for quote, html: { class: "quote form" } do |f| %>
    <% if quote.errors.any? %>
      <div class="error-message">
        <%= quote.errors.full_messages.to_sentence.capitalize %>
      </div>
    <% end %>

    <%= f.input :name, input_html: { autofocus: true } %>
    <%= link_to "Cancel", quotes_path, class: "btn btn--light" %>
    <%= f.submit class: "btn btn--secondary" %>
  <% end %>
<% end %>

app/views/quotes/_quote.html.erb
<%#=
    I believe when a user clicks on the "Cancel" button when editing a quote,
    then the server redirects the user to the #index page. Because this
    _quote.html.erb partial contains the HTML for this given quote, it'll
    replace the edit form that the user had opened before canceling...
    In this case, the turbo_frame below is the "target" page.
%>
<%= turbo_frame_tag(quote) do %>
  <div class="quote">
    <%= link_to quote.name,
                edit_quote_path(quote)
    %>
    <div class="quote__actions">
      <%= link_to "Edit",
                  edit_quote_path(quote),
                  class: "btn btn--light" %>
    </div>
  </div>
<% end %>

<%= turbo_frame_tag "find_author", data: { controller: "button" } do %>
  <%= button_to "Find Author",
              find_author_quote_path(quote),
              method: :get,
              class: "btn btn--primary",
              data: { action: "click->button#disable", button_target: "button" } %>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%#=
  The line below tells Turbo to prepend the turbo_frame with id "quotes"
  the _quote.html.erb partial.
  The "@quote" that follows is equivalent to the following expression:
    render partial: "quotes/quote", locals: { quote: @quote }
%>
<%= turbo_stream.prepend "quotes", @quote %>

<%#=
  Meanwhile, the line below tells Turbo to update the turbo frame with
  id "new_quote" with empty content. This is because after we create a
  new quote, we want to render the 'new_quote' frame as empty. Otherwise,
  we'll always see a form to create a new quote after we submit the form
  to create a quote.
%>
<%= turbo_stream.update Quote.new, "" %>

<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>Edit quote</h1>
  </div>

  <%#=
    Turbo frame that originally included the form partial below has now
    been added instead INSIDE the form, for the purposes of returning
    just the form content within the turbo frame tag, instead of returning
    the entire edit partial.
  %>
  <%= render "form", quote: @quote %>
</main>

app/views/quotes/find_author.turbo_stream.erb
<%= turbo_frame_tag "find_author" do %>
  <%= turbo_stream.update "ai_response", @ai_response %>
<% end %>

app/views/quotes/index.html.erb
<%= turbo_stream_from current_company, "quotes" %>

<main class="container">
  <div class="header">
    <h1>Quote Finder</h1>
    <%#= For now, I will not implement this "New quote" functionality %>
    <%#= link_to "New quote",
                new_quote_path,
                class: "btn btn--primary",
                data: { turbo_frame: dom_id(Quote.new) }
        # Because the turbo_frame_tag below is empty, we need to
        # utilize the data_turbo_frame attribute to connect this
        # link to the new quote form to the turbo frame below.
        # Also, because this link now has Turbo, when a user clicks
        # on this link, Turbo will turn this request into AJAX and
        # will look for a frame id of 'new_quote'. When the server
        # responds with HTML associated with the #new partial, Turbo
        # will extract just the turbo frame with the id of 'new_quote'
        # and render it in the place of the turbo frame below!
    %>
  </div>
  <div>
    <p class="intro-text">
      Ever have that urge to figure out who said a certain quote, but you have no idea who said it?
    </p>
    <p class="intro-text">
      Rejoice! For the handy quote editor will help you figure out the author of your quote, even if you're not
      able to remember the exact wording!
    </p>
    <p class="intro-text">
      To get started, click on the <b>Find Author</b> button for your
      quote and wait a few seconds for the helpful AI to pinpoint who may
      be the author of your particular quote. Feel free to edit the quote
      and find the author of your new quote!
    </p>
  </div>

  <%= render @quotes %>

  <%= turbo_frame_tag "ai_response" %>
</main>

app/views/quotes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <div class="header">
    <h1>New quote</h1>
  </div>

  <%#=
    On this 'new' partial, the 'turbo_frame_tag @quote' is the same
    as 'turbo_frame_tag "new_quote"'. When a user clicks on the "New Quote"
    link on the index page, the server will render this partial in response,
    but Turbo will extract just the frame below and render it on the target
    page, which in this case, is back on the index page!
  %>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
  </div>
</main>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.update "ai_response", "" %>
<%= turbo_stream.remove "find_author" %>